services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gent-chatbot
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Bangkok
      - GEMINI_API_KEY=AIzaSyC0a0lwY2mjXYVMBrfLsMUrK094xeUQTgo
      - GEMINI_API_KEY_2=AIzaSyA5C4CcfYo1jkKwZiWKzL4yDu4bXkNpMWs
      - MONGODB_URI=mongodb+srv://paint:2546paint@cluster0.nmil3pa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - CEM_API_URL=http://172.30.101.52:3001/api
      - CEM_USERNAME=weraprat@gent-s.com
      - CEM_PASSWORD=2546paint
      - AZURE_CLIENT_ID=997e1b06-042a-45e6-b2bc-a42957c57228
      - AZURE_CLIENT_SECRET=kN58Q~c~hIRuX_FlqVn-2fY.L~0-WaaK22_YQdcM
      - AZURE_TENANT_ID=c5fc1b2a-2ce8-4471-ab9d-be65d8fe0906
      - PORT=3002
    restart: unless-stopped
    network_mode: host
